# Use an official Python runtime as a parent image with a specific version
FROM python:3.11
# Set the working directory in the container
WORKDIR /usr/src/app
# Copy the current directory contents into the container at /usr/src/app
COPY hello.py /usr/src/app
# Run hello.py when the container launches
CMD ["python", "./hello.py"]
